[package]
name = "tunder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.34.0"
wintun = "0.2.1"
tokio = { version = "1.17.0", features = ["rt", "macros", "rt-multi-thread", "signal", "sync", "io-util"] }
winapi = "0.3.9"
futures = "0.3.21"
oneshot = "0.1.3"
log = "0.4.16"
env_logger = "0.9.0"
get-last-error = "0.1.0"
etherparse = "0.10.1"
widestring = "0.5.1"
rand = "0.8.5"
libloading = "0.7.3"

[build-dependencies]
bindgen = { version = "0.59.2", features = ["static"], default-features = false }
