[package]
name = "tunio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["rt"] }
log = "0.4.16"
get-last-error = "0.1.0" # replace with Error::last_os_error
widestring = "0.5.1"
uuid = { version = "0.8.2", features = ["v4"]}
bytes = "1.1.0"
crossbeam-channel = "0.5.4"
wintun-sys = { path = "../wintun-sys" }
windows = { version = "0.34.0", features = ["Win32_System_Threading", "Win32_Foundation", "Win32_Security", "Win32_System_WindowsProgramming"] }

[build-dependencies]
bindgen = { version = "0.59.2", features = ["static"], default-features = false }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["rt", "macros", "rt-multi-thread", "signal", "sync", "io-util"] }
etherparse = "0.10.1"
env_logger = "0.9.0"
