[package]
name = "tunio-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
futures = "0.3.21"
netconfig = { version = "0.2.0", path = "../../../netconfig" }
derive_builder = "0.11.2"
delegate = "0.8.0"
tunio-core = { version = "0.1.0", path = "../../core" }
nix = "0.25.0"
libc = "0.2.126"

[features]
tokio = ["tunio-core/tokio"]
