name: Wintun-sys

on:
  push:
    branches: [ main ]
    tags: [ 'wintun_sys-v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - name: Check if can be packaged
      uses: actions-rs/cargo@v1
      with:
        command: package
        args: -p wintun-sys

  publish:
    runs-on: windows-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v3
      - name: Publish to Crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p wintun-sys
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
